[entryPoints]
    [entryPoints.http]
        address = ":80" # will be overriden
    [entryPoints.https]
        address = ":443"

[frontends]
    [frontends.frontend1]
        backend = "backend1"

    [frontends.frontend2]
        backend = "backend2"
            [frontends.frontend2.routes.test_1]
                rule = "Path:/api"

[backends]
    [backends.backend1]
        [backends.backend1.servers.server1]
        url = "https://pdes-2018-todo-list-front.herokuapp.com/"
        # weight = 1 # This is used if there are multiple servers present for load balancing
    [backends.backend2]
        [backends.backend2.servers.server1]
        url = "https://pdes-2018-todo-list-back.herokuapp.com/"